"""Command-line controllers for scraper workflows."""

from __future__ import annotations

import argparse
from collections.abc import Callable, Sequence
import sys

from forexcalendar_scraper.bootstrap import (
    build_calendar_scraper_service,
    build_detail_extraction_service,
    build_detail_query_service,
    build_history_extraction_service,
    build_history_news_extraction_service,
    build_news_extraction_service,
)
from forexcalendar_scraper.core.constants import DEFAULT_EXTRACTOR_DATE_PARAM, DEFAULT_SCRAPER_DATE_PARAM
from forexcalendar_scraper.core.exceptions import ForexCalendarError


CommandHandler = Callable[[argparse.Namespace], int]


def _raw_text_parser(**kwargs: object) -> argparse.ArgumentParser:
    return argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        **kwargs,
    )


def configure_scraper_parser(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    parser.description = "Scrape ForexFactory calendar events into the dated outputs folder."
    parser.epilog = """
Examples:
    forexcalendar-scrape
    forexcalendar-scrape --date-param day=oct6.2025
    python3 -m forexcalendar_scraper scrape --date-param week=oct21.2025
"""
    parser.add_argument(
        "--date-param",
        "--url-params",
        dest="date_param",
        default=DEFAULT_SCRAPER_DATE_PARAM,
        help="ForexFactory date parameter such as day=oct6.2025 or week=oct21.2025.",
    )
    return parser


def configure_extractor_parser(
    parser: argparse.ArgumentParser,
    description: str,
    examples: str,
) -> argparse.ArgumentParser:
    parser.description = description
    parser.epilog = examples
    parser.add_argument(
        "--csv-file",
        type=str,
        help="Path to the base events CSV. Defaults to the dated output file for the date parameter.",
    )
    parser.add_argument(
        "--date-param",
        type=str,
        default=DEFAULT_EXTRACTOR_DATE_PARAM,
        help="ForexFactory date parameter such as day=oct22.2025.",
    )
    return parser


def configure_query_details_parser(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    parser.description = "Query a vertical-block details CSV generated by the detail extractor."
    parser.epilog = """
Examples:
    forexcalendar-query-details
    forexcalendar-query-details --list-fields
    forexcalendar-query-details --event 1
    python3 -m forexcalendar_scraper query-details --field description
    python3 -m forexcalendar_scraper query-details --event 2 --field speaker
"""
    parser.add_argument(
        "--file",
        type=str,
        help="Details CSV to query. Defaults to the most recently modified *_details.csv under outputs/.",
    )
    parser.add_argument("--event", type=str, help="Event ID to query.")
    parser.add_argument("--field", type=str, help="Field name to query.")
    parser.add_argument(
        "--list-fields",
        action="store_true",
        help="List every unique field across all events.",
    )
    return parser


def build_scraper_parser() -> argparse.ArgumentParser:
    return configure_scraper_parser(_raw_text_parser(prog="forexcalendar-scrape"))


def build_detail_extractor_parser() -> argparse.ArgumentParser:
    return configure_extractor_parser(
                _raw_text_parser(prog="forexcalendar-detail-extract"),
        "Extract detailed metadata blocks for events that have ForexFactory detail IDs.",
        """
Examples:
    forexcalendar-detail-extract
    forexcalendar-detail-extract --date-param day=oct22.2025
    python3 -m forexcalendar_scraper details --csv-file outputs/oct-22-2025/day=oct22.2025.csv
""",
    )


def build_history_extractor_parser() -> argparse.ArgumentParser:
    return configure_extractor_parser(
                _raw_text_parser(prog="forexcalendar-history-extract"),
        "Extract historical release data for events that have ForexFactory detail IDs.",
        """
Examples:
    forexcalendar-history-extract
    forexcalendar-history-extract --date-param day=oct22.2025
    python3 -m forexcalendar_scraper history --csv-file outputs/oct-22-2025/day=oct22.2025.csv
""",
    )


def build_news_extractor_parser() -> argparse.ArgumentParser:
    return configure_extractor_parser(
                _raw_text_parser(prog="forexcalendar-news-extract"),
        "Extract related news links for events that have ForexFactory detail IDs.",
        """
Examples:
    forexcalendar-news-extract
    forexcalendar-news-extract --date-param day=oct22.2025
    python3 -m forexcalendar_scraper news --csv-file outputs/oct-22-2025/day=oct22.2025.csv
""",
    )


def build_history_news_extractor_parser() -> argparse.ArgumentParser:
    return configure_extractor_parser(
                _raw_text_parser(prog="forexcalendar-history-news-extract"),
        "Extract both historical release data and related news links in one pass.",
        """
Examples:
    forexcalendar-history-news-extract
    forexcalendar-history-news-extract --date-param day=oct22.2025
    python3 -m forexcalendar_scraper history-news --csv-file outputs/oct-22-2025/day=oct22.2025.csv
""",
    )


def build_query_details_parser() -> argparse.ArgumentParser:
    return configure_query_details_parser(_raw_text_parser(prog="forexcalendar-query-details"))


def build_main_parser() -> argparse.ArgumentParser:
    parser = _raw_text_parser(
        prog="python -m forexcalendar_scraper",
        description="Unified entrypoint for the ForexFactory scraping workflows.",
        epilog="Use one of the subcommands to scrape, extract, or query generated files.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    scrape_parser = configure_scraper_parser(
        subparsers.add_parser(
            "scrape",
            help="Scrape the base calendar event list.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    )
    scrape_parser.set_defaults(handler=_run_scraper_command)

    details_parser = configure_extractor_parser(
        subparsers.add_parser(
            "details",
            help="Extract event details.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
        ),
        "Extract detailed metadata blocks for events that have ForexFactory detail IDs.",
        "",
    )
    details_parser.set_defaults(handler=_run_detail_extractor_command)

    history_parser = configure_extractor_parser(
        subparsers.add_parser(
            "history",
            help="Extract event history.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
        ),
        "Extract historical release data for events that have ForexFactory detail IDs.",
        "",
    )
    history_parser.set_defaults(handler=_run_history_extractor_command)

    news_parser = configure_extractor_parser(
        subparsers.add_parser(
            "news",
            help="Extract related news links.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
        ),
        "Extract related news links for events that have ForexFactory detail IDs.",
        "",
    )
    news_parser.set_defaults(handler=_run_news_extractor_command)

    history_news_parser = configure_extractor_parser(
        subparsers.add_parser(
            "history-news",
            help="Extract both history and news in one pass.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
        ),
        "Extract both historical release data and related news links in one pass.",
        "",
    )
    history_news_parser.set_defaults(handler=_run_history_news_extractor_command)

    query_parser = configure_query_details_parser(
        subparsers.add_parser(
            "query-details",
            help="Query a generated details CSV.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    )
    query_parser.set_defaults(handler=_run_query_details_command)

    return parser


def _run_with_error_handling(handler: CommandHandler, args: argparse.Namespace) -> int:
    try:
        return handler(args)
    except (ForexCalendarError, OSError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


def _display_path(service: object, key: str, result: object) -> str:
    output_file = result.output_files[key]
    return service.path_service.display_path(output_file)


def _run_scraper_command(args: argparse.Namespace) -> int:
    service = build_calendar_scraper_service()
    result = service.run(date_param=args.date_param)
    if "events" not in result.output_files:
        print("No events found to save")
        return 0

    print(
        "Scraped "
        f"{result.written_counts['events']} events and saved to {_display_path(service, 'events', result)}"
    )
    return 0


def _run_detail_extractor_command(args: argparse.Namespace) -> int:
    service = build_detail_extraction_service()
    result = service.run(csv_file=args.csv_file, date_param=args.date_param)
    if "details" not in result.output_files:
        print("No event details found to save")
        return 0

    print(
        "Extracted "
        f"{result.written_counts['details']} event details and saved to {_display_path(service, 'details', result)}"
    )
    return 0


def _run_history_extractor_command(args: argparse.Namespace) -> int:
    service = build_history_extraction_service()
    result = service.run(csv_file=args.csv_file, date_param=args.date_param)
    if "history" not in result.output_files:
        print("No history data found to save")
        return 0

    print(
        "Extracted "
        f"{result.written_counts['history']} history records and saved to {_display_path(service, 'history', result)}"
    )
    return 0


def _run_news_extractor_command(args: argparse.Namespace) -> int:
    service = build_news_extraction_service()
    result = service.run(csv_file=args.csv_file, date_param=args.date_param)
    if "news" not in result.output_files:
        print("No news data found to save")
        return 0

    print(
        "Extracted "
        f"{result.written_counts['news']} news items and saved to {_display_path(service, 'news', result)}"
    )
    return 0


def _run_history_news_extractor_command(args: argparse.Namespace) -> int:
    service = build_history_news_extraction_service()
    result = service.run(csv_file=args.csv_file, date_param=args.date_param)
    messages: list[str] = []
    if "history" in result.output_files:
        messages.append(
            f"{result.written_counts['history']} history records -> {_display_path(service, 'history', result)}"
        )
    if "news" in result.output_files:
        messages.append(
            f"{result.written_counts['news']} news items -> {_display_path(service, 'news', result)}"
        )

    if not messages:
        print("No history or news data found to save")
        return 0

    print("Saved " + "; ".join(messages))
    return 0


def _run_query_details_command(args: argparse.Namespace) -> int:
    service = build_detail_query_service()
    filename, auto_discovered = service.resolve_details_file(args.file)
    if auto_discovered:
        print(f"Using most recent file: {service.path_service.display_path(filename)}\n")

    events = service.load_details(filename)
    if not events:
        print("No events found in the CSV file.", file=sys.stderr)
        return 1

    if args.list_fields:
        output = service.list_all_fields(events)
    elif args.event and args.field:
        output = service.show_specific_field(events, args.event, args.field)
    elif args.event:
        output = service.show_event(events, args.event)
    elif args.field:
        output = service.show_field_across_events(events, args.field)
    else:
        output = service.list_all_events(events)

    print(output, end="")
    return 0


def run_scraper_cli(argv: Sequence[str] | None = None) -> int:
    args = build_scraper_parser().parse_args(argv)
    return _run_with_error_handling(_run_scraper_command, args)


def run_detail_extractor_cli(argv: Sequence[str] | None = None) -> int:
    args = build_detail_extractor_parser().parse_args(argv)
    return _run_with_error_handling(_run_detail_extractor_command, args)


def run_history_extractor_cli(argv: Sequence[str] | None = None) -> int:
    args = build_history_extractor_parser().parse_args(argv)
    return _run_with_error_handling(_run_history_extractor_command, args)


def run_news_extractor_cli(argv: Sequence[str] | None = None) -> int:
    args = build_news_extractor_parser().parse_args(argv)
    return _run_with_error_handling(_run_news_extractor_command, args)


def run_history_news_extractor_cli(argv: Sequence[str] | None = None) -> int:
    args = build_history_news_extractor_parser().parse_args(argv)
    return _run_with_error_handling(_run_history_news_extractor_command, args)


def run_query_details_cli(argv: Sequence[str] | None = None) -> int:
    args = build_query_details_parser().parse_args(argv)
    return _run_with_error_handling(_run_query_details_command, args)


def main(argv: Sequence[str] | None = None) -> int:
    args = build_main_parser().parse_args(argv)
    handler = args.handler
    return _run_with_error_handling(handler, args)


if __name__ == "__main__":
    raise SystemExit(main())